=== wcmaclean/home-repo/Java/XML/WeatherServer/theWeather.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="theWeather">
  <xs:complexType>
    <xs:sequence>

      <xs:element name="locationName" minOccurs="1" maxOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Chicago"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="locationCode" minOccurs="1" maxOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CHI"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="weather" maxOccurs="unbounded">
        <xs:complexType>

          <xs:sequence>
            <xs:element name="dateTime" type="xs:string"/>
            <xs:element name="windSpeed" type="xs:integer"/>
            <xs:element name="windDirection" type="xs:string"/>
            <xs:element name="barometricPressure" type="xs:integer"/>
            <xs:element name="relativeHumidity" type="xs:integer"/>
            <xs:element name="dewPointTemp" type="xs:integer"/>
            <xs:element name="precipitationLast24Hours" type="xs:integer"/>
            <xs:element name="currentHighLast24Hours" type="xs:integer"/>
            <xs:element name="currentLowLast24Hours" type="xs:integer"/>
            <xs:element name="snowfallLast24Hours" type="xs:integer"/>
            <xs:element name="heatIndex" type="xs:integer"/>
            <xs:element name="windChill" type="xs:integer"/>
            <xs:element name="officialWarnings" type="xs:string"/>
            <xs:element name="officialWatches" type="xs:string"/>

          </xs:sequence>
        </xs:complexType>  
      </xs:element>

    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== wcmaclean/home-repo/Java/XML/WeatherServer/weather.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="weather.xsl"  type="text/xsl"?>


<theWeather xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./theWeather.xsd">


<locationName>Chicago</locationName>

<locationCode>CHI</locationCode>


<weather>

<dateTime>2/9/2006 21:29:53:957</dateTime>

<windSpeed>12</windSpeed>

<windDirection>West</windDirection>

<barometricPressure>46</barometricPressure>

<relativeHumidity>15</relativeHumidity>

<dewPointTemp>5</dewPointTemp>

<precipitationLast24Hours>7</precipitationLast24Hours>

<currentHighLast24Hours>47</currentHighLast24Hours>

<currentLowLast24Hours>44</currentLowLast24Hours>

<snowfallLast24Hours>0</snowfallLast24Hours>

<heatIndex>0</heatIndex>

<windChill>5</windChill>

<officialWarnings>Tropical Storm</officialWarnings>

<officialWatches>Timex</officialWatches>

</weather>

</theWeather>
